Repository AP-Back/Web-Dev-Projects, pull requests merged in 2022-10, with the labels that each got.

#2 Add Pull Request Template
  PR.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#3 Add VM link project
  VM-LINK/css/center.css
  VM-LINK/css/payment_style.css
  VM-LINK/css/style.css
  VM-LINK/images/download.png
  VM-LINK/images/fe1.png
  VM-LINK/images/fe2.png
  VM-LINK/images/fe3.png
  VM-LINK/images/home-bg.jpg
  VM-LINK/images/home-img.png
  VM-LINK/images/p1.png
  VM-LINK/images/p2.png
  VM-LINK/images/p3.png
  VM-LINK/images/pic1.png
  VM-LINK/images/pic2.png
  VM-LINK/images/pic3.png
  VM-LINK/images/pic4.png
  VM-LINK/images/port-img1.jpg
  VM-LINK/images/port-img2.jpg
  VM-LINK/images/port-img3.jpg
  VM-LINK/images/port-img4.jpg
  VM-LINK/images/port-img5.jpg
  VM-LINK/images/port-img6.jpg
  VM-LINK/images/s1.png
  VM-LINK/images/s2.png
  VM-LINK/images/s3.png
  VM-LINK/images/s4.png
  VM-LINK/images/s5.png
  VM-LINK/index.html
  VM-LINK/js/script.js
  VM-LINK/js/script1.js
  VM-LINK/payment.html
  VM-LINK/paymentsuccess.html
  VM-LINK/resources/Cart.svg
  VM-LINK/resources/Profile.svg
  VM-LINK/resources/Search.svg
  VM-LINK/resources/check.svg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#4 Added cocktails-project
  README.md
  Readme.md
  cocktails-project/.gitignore
  cocktails-project/README.md
  cocktails-project/package-lock.json
  cocktails-project/package.json
  cocktails-project/postcss.config.js
  cocktails-project/public/favicon.ico
  cocktails-project/public/index.html
  cocktails-project/public/logo192.png
  cocktails-project/public/logo512.png
  cocktails-project/public/manifest.json
  cocktails-project/public/robots.txt
  cocktails-project/src/App.js
  cocktails-project/src/components/About.js
  cocktails-project/src/components/AboutCockTail.js
  cocktails-project/src/components/BackHomeButton.js
  cocktails-project/src/components/Cocktails.js
  cocktails-project/src/components/Home.js
  cocktails-project/src/components/Nav.js
  cocktails-project/src/img/logo.svg
  cocktails-project/src/index.css
  cocktails-project/src/index.js
  cocktails-project/tailwind.config.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 Happy-Birthday Project Added
  Happy-Birthday/function.js
  Happy-Birthday/index.html
  Happy-Birthday/style.css
Labels: hacktoberfest, hacktoberfest2022

#10 Add django todolist app
  django-todo-app/.gitignore
  django-todo-app/README.md
  django-todo-app/package-lock.json
  django-todo-app/package.json
  django-todo-app/public/favicon.ico
  django-todo-app/public/index.html
  django-todo-app/public/logo192.png
  django-todo-app/public/logo512.png
  django-todo-app/public/manifest.json
  django-todo-app/public/robots.txt
  django-todo-app/src/App.css
  django-todo-app/src/App.js
  django-todo-app/src/App.test.js
  django-todo-app/src/index.css
  django-todo-app/src/index.js
  django-todo-app/src/logo.svg
  django-todo-app/src/reportWebVitals.js
  django-todo-app/src/setupTests.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Added Roll Hold Win Game
  ROLL_HOLD_WIN_GAME/images/dice1.png
  ROLL_HOLD_WIN_GAME/images/dice2.png
  ROLL_HOLD_WIN_GAME/images/dice3.png
  ROLL_HOLD_WIN_GAME/images/dice4.png
  ROLL_HOLD_WIN_GAME/images/dice5.png
  ROLL_HOLD_WIN_GAME/images/dice6.png
  ROLL_HOLD_WIN_GAME/logic/home.js
  ROLL_HOLD_WIN_GAME/logic/script1v1.js
  ROLL_HOLD_WIN_GAME/logic/script1vpc.js
  ROLL_HOLD_WIN_GAME/pages/game1v1.html
  ROLL_HOLD_WIN_GAME/pages/game1vpc.html
  ROLL_HOLD_WIN_GAME/pages/home.html
  ROLL_HOLD_WIN_GAME/style/home.css
  ROLL_HOLD_WIN_GAME/style/mydetails.css
  ROLL_HOLD_WIN_GAME/style/style.css
  Readme.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 Calculator code added
  Calculator/index.html
  Calculator/script.js
  Calculator/style.css
  Readme.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 Learn React
  Learn-React/.gitignore
  Learn-React/README.md
  Learn-React/package-lock.json
  Learn-React/package.json
  Learn-React/public/favicon.ico
  Learn-React/public/index.html
  Learn-React/public/logo192.png
  Learn-React/public/logo512.png
  Learn-React/public/manifest.json
  Learn-React/public/robots.txt
  Learn-React/src/01-intro.js
  Learn-React/src/02-nested_componentss.js
  Learn-React/src/03-booklist.js
  Learn-React/src/04-booklist_props.js
  Learn-React/src/05-booklist_props_array_object.js
  Learn-React/src/06-event_handling.js
  Learn-React/src/07-Book.js
  Learn-React/src/07-Book_List.js
  Learn-React/src/07-index.js
  Learn-React/src/book.jpg
  Learn-React/src/index.css
  Learn-React/src/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#19 Added movies-db react-tailwind project
  movies-db/.gitignore
  movies-db/README.md
  movies-db/package-lock.json
  movies-db/package.json
  movies-db/postcss.config.js
  movies-db/public/README.md
  movies-db/public/_redirects
  movies-db/public/favicon.ico
  movies-db/public/index.html
  movies-db/public/logo192.png
  movies-db/public/logo512.png
  movies-db/public/manifest.json
  movies-db/public/robots.txt
  movies-db/src/index.css
  movies-db/src/index.js
  movies-db/src/movies/App.js
  movies-db/src/movies/HelmetHeader.js
  movies-db/src/movies/components/FormInput.js
  movies-db/src/movies/components/Home.js
  movies-db/src/movies/components/ShowMovieDetails.js
  movies-db/src/movies/components/ShowMovies.js
  movies-db/tailwind.config.js
  taskmanager-api/.gitignore
  taskmanager-api/API-documentation.md
  taskmanager-api/README.md
  taskmanager-api/app/app.js
  taskmanager-api/app/controller/taskController.js
  taskmanager-api/app/errors/customError.js
  taskmanager-api/app/middleware/asyncWrapper.js
  taskmanager-api/app/middleware/errorHandler.js
  taskmanager-api/app/middleware/notFound.js
  taskmanager-api/app/model/task.js
  taskmanager-api/app/routes/taskRoutes.js
  taskmanager-api/db/connect.js
  taskmanager-api/package-lock.json
  taskmanager-api/package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
