Repository AP-Back/Web-Dev-Projects, pull requests merged in 2023-10, with the labels that each got.

#21 Added Readme Template
  Readme.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#20 Adding Car Rental portal
  car-rental-portal/.gitignore
  car-rental-portal/README.md
  car-rental-portal/package-lock.json
  car-rental-portal/package.json
  car-rental-portal/public/index.html
  car-rental-portal/src/App.css
  car-rental-portal/src/App.js
  car-rental-portal/src/components/CarCard.js
  car-rental-portal/src/components/Cars.js
  car-rental-portal/src/components/Footer.js
  car-rental-portal/src/components/Header.js
  car-rental-portal/src/data/cars.json
  car-rental-portal/src/index.js
  car-rental-portal/tailwind.config.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#22 Added Enconnect Project
  EnConnect/.firebase/hosting.YnVpbGQ.cache
  EnConnect/.gitignore
  EnConnect/cssdump.css
  EnConnect/package-lock.json
  EnConnect/package.json
  EnConnect/public/favicon.ico
  EnConnect/public/index.html
  EnConnect/public/manifest.json
  EnConnect/public/robots.txt
  EnConnect/src/App.css
  EnConnect/src/App.js
  EnConnect/src/App.test.js
  EnConnect/src/components/chatheads/ChatHeads.jsx
  EnConnect/src/components/chatheads/chatheads.css
  EnConnect/src/components/conversation/Conversation.jsx
  EnConnect/src/components/conversation/conversation.css
  EnConnect/src/components/navbar/Navbar.jsx
  EnConnect/src/components/navbar/favicon.ico
  EnConnect/src/components/navbar/navbar.css
  EnConnect/src/firebase.js
  EnConnect/src/index.css
  EnConnect/src/index.js
  EnConnect/src/logo.svg
  EnConnect/src/reportWebVitals.js
  EnConnect/src/screens/chat-screen/ChatScreen.jsx
  EnConnect/src/screens/chat-screen/chat-screen.css
  EnConnect/src/screens/login-screen/LoginScreen.jsx
  EnConnect/src/screens/login-screen/login-screen.css
  EnConnect/src/setupTests.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#25 Added Amazon clone
  amazon-clone/.eslintrc.json
  amazon-clone/.gitignore
  amazon-clone/README.md
  amazon-clone/next.config.js
  amazon-clone/package-lock.json
  amazon-clone/package.json
  amazon-clone/postcss.config.js
  amazon-clone/public/favicon.ico
  amazon-clone/public/next.svg
  amazon-clone/public/vercel.svg
  amazon-clone/src/components/Banner.tsx
  amazon-clone/src/components/BottomHeader.tsx
  amazon-clone/src/components/CartPayment.tsx
  amazon-clone/src/components/CartProduct.tsx
  amazon-clone/src/components/FavoriteProduct.tsx
  amazon-clone/src/components/Footer.tsx
  amazon-clone/src/components/FormattedPrice.tsx
  amazon-clone/src/components/Header.tsx
  amazon-clone/src/components/Products.tsx
  amazon-clone/src/components/ResetCart.tsx
  amazon-clone/src/components/ResetFavoriteItems.tsx
  amazon-clone/src/components/RootLayout.tsx
  amazon-clone/src/components/SearchProducts.tsx
  amazon-clone/src/images/cartIcon.png
  amazon-clone/src/images/logo.png
  amazon-clone/src/images/slider/sliderImg_1.jpg
  amazon-clone/src/images/slider/sliderImg_2.jpg
  amazon-clone/src/images/slider/sliderImg_3.jpg
  amazon-clone/src/images/slider/sliderImg_4.jpg
  amazon-clone/src/images/slider/sliderImg_5.jpg
  amazon-clone/src/pages/[_id].tsx
  amazon-clone/src/pages/_app.tsx
  amazon-clone/src/pages/_document.tsx
  amazon-clone/src/pages/api/auth/[...nextauth].ts
  amazon-clone/src/pages/api/checkout.ts
  amazon-clone/src/pages/api/hello.ts
  amazon-clone/src/pages/cart.tsx
  amazon-clone/src/pages/favorite.tsx
  amazon-clone/src/pages/index.tsx
  amazon-clone/src/pages/success.tsx
  amazon-clone/src/store/nextSlice.ts
  amazon-clone/src/store/store.ts
  amazon-clone/src/styles/globals.css
  amazon-clone/tailwind.config.ts
  amazon-clone/tsconfig.json
  amazon-clone/type.d.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#26 Added CHAT GPT Clone
  chatgpt-clone/.gitignore
  chatgpt-clone/AIChat1_1.png
  chatgpt-clone/LICENSE
  chatgpt-clone/README.md
  chatgpt-clone/app/chat/[id]/page.tsx
  chatgpt-clone/app/layout.tsx
  chatgpt-clone/app/page.tsx
  chatgpt-clone/components/Chat.tsx
  chatgpt-clone/components/ChatInput.tsx
  chatgpt-clone/components/ChatRow.tsx
  chatgpt-clone/components/ClientProvider.tsx
  chatgpt-clone/components/Login.tsx
  chatgpt-clone/components/Message.tsx
  chatgpt-clone/components/ModelSelection.tsx
  chatgpt-clone/components/NewChat.tsx
  chatgpt-clone/components/SessionProvider.tsx
  chatgpt-clone/components/Sidebar.tsx
  chatgpt-clone/firebase.ts
  chatgpt-clone/firebaseAdmin.ts
  chatgpt-clone/lib/chatgpt.ts
  chatgpt-clone/lib/openaiWrapper.ts
  chatgpt-clone/lib/queryApi.ts
  chatgpt-clone/next.config.js
  chatgpt-clone/package-lock.json
  chatgpt-clone/package.json
  chatgpt-clone/pages/_app.tsx
  chatgpt-clone/pages/api/askQuestion.ts
  chatgpt-clone/pages/api/auth/[...nextauth].ts
  chatgpt-clone/pages/api/getEngines.ts
  chatgpt-clone/pages/api/hello.ts
  chatgpt-clone/postcss.config.js
  chatgpt-clone/public/favicon.ico
  chatgpt-clone/public/logo.svg
  chatgpt-clone/public/vercel.svg
  chatgpt-clone/styles/globals.css
  chatgpt-clone/tailwind.config.js
  chatgpt-clone/tsconfig.json
  chatgpt-clone/types/message.ts
  chatgpt-clone/typings.d.ts
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2023

#24 Adding a Chrome Extension that can generate QR from any link
  QR-generation-chrome-extension/index.html
  QR-generation-chrome-extension/js/app.js
  QR-generation-chrome-extension/logo.png
  QR-generation-chrome-extension/manifest.json
  course-search-flask-app/.gitignore
  course-search-flask-app/app.py
  course-search-flask-app/readme.md
  course-search-flask-app/src/__pycache__/pattern_matching.cpython-39.pyc
  course-search-flask-app/src/pattern_matching.py
  course-search-flask-app/src/static/style.css
  course-search-flask-app/src/template/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#27 Adding a Bulk mailer app using Nodemailer
  bulk-mailer/.env
  bulk-mailer/.gitignore
  bulk-mailer/controllers/mailSender.js
  bulk-mailer/package-lock.json
  bulk-mailer/package.json
  bulk-mailer/public/index.html
  bulk-mailer/routes/mainRouter.js
  bulk-mailer/server.js
  bulk-mailer/templates/email.ejs
  bulk-mailer/uploads/data.csv
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#28 Adding Tic tac toe game
  tic-tac-toe/index.html
  tic-tac-toe/script.js
  tic-tac-toe/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2023

#29 Adding Pushing Pixels Project
  pushing-pixels/README.md
  pushing-pixels/bg.jpg
  pushing-pixels/favicon.ico
  pushing-pixels/index.html
  pushing-pixels/light-switch.png
  pushing-pixels/lightbulb.png
  pushing-pixels/logo-shadow.png
  pushing-pixels/logo.png
  pushing-pixels/script.js
  pushing-pixels/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
